import React from "react";
import {
  Col,
  Row,
  Button,
  Form,
  FormGroup,
  Label,
  Input,
  Card,
  CardHeader,
  CardBody,
  Table
} from "reactstrap";

const UgDegreeDetails = ({ setForm, formData, navigation }) => {
  const {
    ugDegree,
    collegeName,
    collegeAddress,
    universityAddress,
    nameOfUniversity,
    IsemMonth,
    Isemyop,
    Isemmaxmarks,
    Isemmarks,
    IIsemMonth,
    IIsemyop,
    IIsemmaxmarks,
    IIsemmarks,
    IIIsemMonth,
    IIIsemyop,
    IIIsemmaxmarks,
    IIIsemmarks,
    IVsemMonth,
    IVsemyop,
    IVsemmaxmarks,
    IVsemmarks,
    VsemMonth,
    Vsemyop,
    Vsemmaxmarks,
    Vsemmarks,
    VIsemMonth,
    VIsemyop,
    VIsemmaxmarks,
    VIsemmarks,
    VIIsemMonth,
    VIIsemyop,
    VIIsemmaxmarks,
    VIIsemmarks,
    VIIIsemMonth,
    VIIIsemyop,
    VIIIsemmaxmarks,
    VIIIsemmarks,
    IXsemMonth,
    IXsemyop,
    IXsemmaxmarks,
    IXsemmarks,
    XsemMonth,
    Xsemyop,
    Xsemmaxmarks,
    Xsemmarks,
    overalltot,
    overallmarks,
    totalpermark
  } = formData;

  const { next, previous } = navigation;

  return (
    <Form>
      <Card>
        <CardHeader>
          Details of Marks in UG Degree Qualifying Examinations
        </CardHeader>
        <CardBody>
          <Row form>
            <Col md={6}>
              <FormGroup>
                <Label for="ugDegree">UG Degree</Label>
                <Input
                  type="text"
                  name="ugDegree"
                  id="ugDegree"
                  key="ugDegree"
                  value={ugDegree}
                  onChange={setForm}
                  placeholder="UG Degree"
                />
              </FormGroup>
            </Col>
            <Col md={6}>
              <FormGroup>
                <Label for="collegeName">Name Of The College</Label>
                <Input
                  type="name"
                  name="collegeName"
                  id="collegeName"
                  key="collegeName"
                  value={collegeName}
                  onChange={setForm}
                  placeholder="Name"
                />
              </FormGroup>
            </Col>
          </Row>
          <Row form>
            <Col md={6}>
              <FormGroup>
                <Label for="collegeAddress">College Address</Label>
                <Input
                  type="text"
                  name="collegeAddress"
                  id="collegeAddress"
                  key="collegeAddress"
                  value={collegeAddress}
                  onChange={setForm}
                  placeholder="Parent Name"
                />
              </FormGroup>
            </Col>
            <Col md={6}>
              <FormGroup>
                <Label for="nameOfUniversity">Name Of The University</Label>
                <Input
                  type="text"
                  name="nameOfUniversity"
                  id="nameOfUniversity"
                  key="nameOfUniversity"
                  value={nameOfUniversity}
                  onChange={setForm}
                  placeholder="Parent Name"
                />
              </FormGroup>
            </Col>
            <Col md={7}>
              <FormGroup>
                <Label for="universityAddress">Address of The University</Label>
                <Input
                  type="text"
                  name="universityAddress"
                  id="universityAddress"
                  key="universityAddress"
                  value={universityAddress}
                  onChange={setForm}
                  placeholder="Parent Name"
                />
              </FormGroup>
            </Col>
          </Row>
          <Table bordered>
            <thead>
              <tr>
                <th>Semester/Year</th>
                <th>Month</th>
                <th>Year Of Passing</th>
                <th>Maximum Marks</th>
                <th>Marks Obtained</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <th scope="row">I</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IsemMonth"
                    id="IsemMonth"
                    key="IsemMonth"
                    value={IsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Isemyop"
                    id="Isemyop"
                    key="Isemyop"
                    value={Isemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Isemmaxmarks"
                    id="Isemmaxmarks"
                    key="Isemmaxmarks"
                    value={Isemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Isemmarks"
                    id="Isemmarks"
                    key="Isemmarks"
                    value={Isemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">II</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIsemMonth"
                    id="IIsemMonth"
                    key="IIsemMonth"
                    value={IIsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIsemyop"
                    id="IIsemyop"
                    key="IIsemyop"
                    value={IIsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIsemmaxmarks"
                    id="IIsemmaxmarks"
                    key="IIsemmaxmarks"
                    value={IIsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIsemmarks"
                    id="IIsemmarks"
                    key="IIsemmarks"
                    value={IIsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">III</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIIsemMonth"
                    id="IIIsemMonth"
                    key="IIIsemMonth"
                    value={IIIsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIIsemyop"
                    id="IIIsemyop"
                    key="IIIsemyop"
                    value={IIIsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIIsemmaxmarks"
                    id="IIIsemmaxmarks"
                    key="IIIsemmaxmarks"
                    value={IIIsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IIIsemmarks"
                    id="IIIsemmarks"
                    key="IIIsemmarks"
                    value={IIIsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">IV</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IVsemMonth"
                    id="IVsemMonth"
                    key="IVsemMonth"
                    value={IVsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IVsemyop"
                    id="IVsemyop"
                    key="IVsemyop"
                    value={IVsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IVsemmaxmarks"
                    id="IVsemmaxmarks"
                    key="IVsemmaxmarks"
                    value={IVsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IVsemmarks"
                    id="IVsemmarks"
                    key="IVsemmarks"
                    value={IVsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">V</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VsemMonth"
                    id="VsemMonth"
                    key="VsemMonth"
                    value={VsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Vsemyop"
                    id="Vsemyop"
                    key="Vsemyop"
                    value={Vsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Vsemmaxmarks"
                    id="Vsemmaxmarks"
                    key="Vsemmaxmarks"
                    value={Vsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Vsemmarks"
                    id="Vsemmarks"
                    key="Vsemmarks"
                    value={Vsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">VI</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIsemMonth"
                    id="VIsemMonth"
                    key="VIsemMonth"
                    value={VIsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIsemyop"
                    id="VIsemyop"
                    key="VIsemyop"
                    value={VIsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIsemmaxmarks"
                    id="VIsemmaxmarks"
                    key="VIsemmaxmarks"
                    value={VIsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIsemmarks"
                    id="VIsemmarks"
                    key="VIsemmarks"
                    value={VIsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">VII</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIsemMonth"
                    id="VIIsemMonth"
                    key="VIIsemMonth"
                    value={VIIsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIsemyop"
                    id="VIIsemyop"
                    key="VIIsemyop"
                    value={VIIsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIsemmaxmarks"
                    id="VIIsemmaxmarks"
                    key="VIIsemmaxmarks"
                    value={VIIsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIsemmarks"
                    id="VIIsemmarks"
                    key="VIIsemmarks"
                    value={VIIsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">VIII</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIIsemMonth"
                    id="VIIIsemMonth"
                    key="VIIIsemMonth"
                    value={VIIIsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIIsemyop"
                    id="VIIIsemyop"
                    key="VIIIsemyop"
                    value={VIIIsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIIsemmaxmarks"
                    id="VIIIsemmaxmarks"
                    key="VIIIsemmaxmarks"
                    value={VIIIsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="VIIIsemmarks"
                    id="VIIIsemmarks"
                    key="VIIIsemmarks"
                    value={VIIIsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">IX</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IXsemMonth"
                    id="IXsemMonth"
                    key="IXsemMonth"
                    value={IXsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IXsemyop"
                    id="IXsemyop"
                    key="IXsemyop"
                    value={IXsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IXsemmaxmarks"
                    id="IXsemmaxmarks"
                    key="IXsemmaxmarks"
                    value={IXsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="IXsemmarks"
                    id="IXsemmarks"
                    key="IXsemmarks"
                    value={IXsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row">X</th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="XsemMonth"
                    id="XsemMonth"
                    key="XsemMonth"
                    value={XsemMonth}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Xsemyop"
                    id="Xsemyop"
                    key="Xsemyop"
                    value={Xsemyop}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Xsemmaxmarks"
                    id="Xsemmaxmarks"
                    key="Xsemmaxmarks"
                    value={Xsemmaxmarks}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="Xsemmarks"
                    id="Xsemmarks"
                    key="Xsemmarks"
                    value={Xsemmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row" colSpan="3">
                  Overall Total
                </th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="overalltot"
                    id="overalltot"
                    key="overalltot"
                    value={overalltot}
                    onChange={setForm}
                  ></input>
                </td>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="overallmarks"
                    id="overallmarks"
                    key="overallmarks"
                    value={overallmarks}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
              <tr>
                <th scope="row" colSpan="4">
                  Total % Of Marks
                </th>
                <td>
                  <input
                    type="text"
                    class="form-control"
                    name="totalpermark"
                    id="totalpermark"
                    key="totalpermark"
                    value={totalpermark}
                    onChange={setForm}
                  ></input>
                </td>
              </tr>
            </tbody>
          </Table>
          <div>
            <Button onClick={previous}>Previous</Button>
            <Button onClick={next}>Next</Button>
          </div>
        </CardBody>
      </Card>
    </Form>
  );
};

export default UgDegreeDetails;
